services:
  mysql:
    image: mysql:8.0
    container_name: ticketflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticketflow-network

networks:
  ticketflow-network:
    driver: bridge

volumes:
  mysql_data:
