server:
  port: 8089

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ticketflow_notification?createDatabaseIfNotExist=true
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://ticketflow-mysql:3306/ticketflow_notification?createDatabaseIfNotExist=true
    username: root
    password: root
